version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: file/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: file/start_server.sh
      timeout: 300
      runas: root
