version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies (if any)..."
  pre_build:
    commands:
      - echo "Preparing the build environment..."
  build:
    commands:
      - echo "Building the application..."
      - echo "Zipping the application files..."
      - zip -r html_app.zip index.html scripts/start_server.sh
  post_build:
    commands:
      - echo "Build process completed successfully."

artifacts:
  files:
    - html_app.zip
    - index.html
    - file/start_server.sh
  discard-paths: yes